{
  "Meat": [
    "rump steak","scotch fillet","porterhouse steak","t-bone steak",
    "beef mince","diced beef","beef schnitzel","beef stir-fry strips",
    "beef sausages","corned beef silverside","beef roast","lamb chops",
    "lamb cutlets","lamb leg roast","lamb shanks","diced lamb",
    "lamb mince","lamb sausages","pork chops","pork belly","pork roast",
    "pork spare ribs","diced pork","pork mince","pork sausages",
    "pork schnitzel","whole chicken","chicken breast","chicken thighs",
    "chicken drumsticks","chicken wings","chicken tenderloins",
    "chicken mince","chicken schnitzel","chicken marylands",
    "roast beef slices","pastrami","corned beef slices","champagne ham",
    "virginian ham","honey leg ham","triple smoked ham",
    "shaved chicken breast","turkey breast slices","salami","prosciutto",
    "sopressa","mortadella","pepperoni","kassler","bacon","frankfurts",
    "kransky","chorizo","cocktail sausages","kabana","devon","liverwurst",
    "pâté","marinated chicken wings","marinated chicken drumsticks",
    "meat kebabs","rissoles","burger patties","honey soy chicken portions",
    "bbq pork ribs","pre-marinated pork belly","lemon herb chicken thighs"
  ],
  "Veg": [
    "apples","bananas","oranges","mandarins","pears","peaches","plums",
    "nectarines","grapes","kiwifruit","pineapple","mangoes","watermelon",
    "rockmelon","cantaloupe","strawberries","blueberries","raspberries",
    "blackberries","lemons","limes","avocados","tomatoes","cherry tomatoes",
    "grape tomatoes","cucumbers","zucchini","carrots","celery","lettuce",
    "cos lettuce","iceberg lettuce","mixed salad leaves","rocket","spinach",
    "silverbeet","kale","cabbage","red cabbage","savoy cabbage","broccoli",
    "cauliflower","green beans","snow peas","sugar snap peas","capsicum",
    "chillies","eggplant","pumpkin","sweet potato","potatoes","onions",
    "yellow onion","brown onion","garlic","shallots","spring onions","leeks",
    "mushrooms","corn","green peas","brussels sprouts","beetroot","radish",
    "fennel","asparagus","artichoke","chokos","passionfruit","papaya",
    "pomegranate","coconut","dates","figs","persimmon","lychee","dragonfruit",
    "rambutan","starfruit",
    "basil","coriander","cilantro","parsley","mint","dill","chives","thyme",
    "rosemary","oregano","sage","tarragon","marjoram","vietnamese mint",
    "lemongrass","kaffir lime leaves","bay leaves","curry leaves"
  ],
  "Dairy": [
    "milk","lactose-free milk","a2 milk","long-life milk","flavoured milk",
    "uht milk","buttermilk","cream","sour cream","crème fraîche","yoghurt",
    "yoghurt tubs","yoghurt pouches","skyr","kefir","butter","cultured butter",
    "spreadable butter","margarine","ghee","cheddar cheese","tasty cheese",
    "colby cheese","mozzarella","parmesan","pecorino","grana padano",
    "swiss cheese","jarlsberg","havarti","provolone","edam","gouda","brie",
    "camembert","blue cheese","feta","goat cheese","ricotta","cottage cheese",
    "cream cheese","mascarpone","paneer","haloumi","processed cheese slices",
    "cheese sticks","shredded cheese blends","grated cheese","sliced cheese packs",
    "parmesan shavings","dairy desserts","custard","milk-based smoothies",
    "dairy-based dips","evaporated milk","condensed milk","powdered milk"
  ],
  "Bakery": [
    "white bread","wholemeal bread","multigrain bread","soy and linseed bread",
    "rye bread","sourdough","pane di casa","ciabatta","turkish bread",
    "brioche loaf","vienna loaf","high-fibre loaf","gluten-free bread",
    "low-carb bread","fruit loaf","raisin toast","english muffins","crumpets",
    "bagels","wraps","tortillas","pita bread","lebanese bread","flatbread",
    "pizza bases","burger buns","hot dog rolls","long rolls","dinner rolls",
    "seeded rolls","mini rolls","cheese and bacon rolls","scrolls","croissants",
    "pain au chocolat","danish pastries","cinnamon scrolls","apple turnovers",
    "custard tarts","jam tarts","vanilla slices","eclairs","lamingtons",
    "swiss rolls","muffins","cupcakes","madeleines","banana bread","carrot cake",
    "mud cake","sponge cake","chocolate cake","birthday cake","slab cake",
    "fruit cake","pound cake","tea cake","butter cake","brownies","slice bars",
    "cookies","biscuits","shortbread","anzac biscuits","gingerbread",
    "melting moments","yo-yos","scones","pikelets","waffles","donuts",
    "mini donuts","jam-filled donuts","iced donuts","cinnamon donuts","churros"
  ],
  "Pantry": [
    "plain flour","self-raising flour","wholemeal flour","bread flour","00 flour",
    "rice flour","cornflour","almond meal","coconut flour","polenta","semolina",
    "rolled oats","quick oats","steel-cut oats","muesli","granola","cereal","pasta",
    "gluten-free pasta","rice","couscous","quinoa","bulgur","barley","lentils",
    "chickpeas","black beans","kidney beans","cannellini beans","butter beans",
    "baked beans","tinned tomatoes","tomato paste","tomato passata","coconut milk",
    "coconut cream","evaporated milk","condensed milk","uht milk","canned corn",
    "canned mushrooms","canned beetroot","canned fruit","tuna","salmon","sardines",
    "anchovies","corned beef","spam","canned chicken","soup cans","stock",
    "low sodium chicken broth","soup mixes","bouillon cubes","gravy powder",
    "packet sauces","instant noodles","2-minute noodles","rice vermicelli",
    "egg noodles","udon noodles","soba noodles","nori sheets","breadcrumbs",
    "crackers","rice cakes","corn cakes","crispbread","biscuits","chocolate biscuits",
    "wafers","muesli bars","nut bars","cake mixes","brownie mix","pudding mix",
    "custard powder","gelatine","baking powder","baking soda","yeast","icing sugar",
    "caster sugar","white sugar","raw sugar","brown sugar","demerara sugar",
    "golden syrup","maple syrup","honey","molasses","agave syrup","peanut butter",
    "almond butter","tahini","hazelnut spread","jam","marmalade","vegemite",
    "promite","marmite","chutney","relish","mustard","mayonnaise","aioli",
    "tomato sauce","bbq sauce","sweet chilli sauce","soy sauce","tamari",
    "teriyaki sauce","hoisin sauce","oyster sauce","fish sauce","sriracha",
    "hot sauce","curry paste","sambal oelek","satay sauce","vinegar","lemon juice",
    "lime juice","olive oil","vegetable oil","canola oil","sunflower oil","sesame oil",
    "peanut oil","coconut oil","ghee","cooking spray","salt","sea salt flakes",
    "iodised salt","himalayan salt","black pepper","peppercorns","mixed herbs",
    "oregano","thyme","rosemary","parsley","basil","sage","chives","bay leaves",
    "chilli flakes","ground paprika","smoked paprika","ground cumin","ground coriander",
    "curry powder","garam masala","five spice","turmeric","cinnamon","nutmeg",
    "allspice","ground ginger","cloves","vanilla extract","vanilla essence",
    "almond essence","food colouring","sprinkles","decorations","cocoa powder",
    "drinking chocolate","hot chocolate mix","instant coffee","ground coffee",
    "coffee beans","coffee pods","black tea bags","green tea","herbal tea",
    "chai tea","iced tea","cordials","soft drink bottles","tonic water",
    "mineral water","sparkling water","long-life juice","cooking wine",
    "stock concentrate","meal bases","taco kits","wraps","tortillas","bread",
    "pizza bases","flatbread","pappadums","pickles","gherkins","olives",
    "sun-dried tomatoes","roasted red peppers","antipasto mix","capers",
    "artichoke hearts","jerky","popcorn","potato chips","corn chips","pretzels",
    "nuts","trail mix","dried fruit","desiccated coconut","shredded coconut",
    "seeds","protein powder","electrolyte powder","multivitamins","health bars",
    "baby formula","baby food jars","pet food","alfoil","cling wrap","baking paper",
    "ziplock bags","lunch bags","paper towels","tissues","toilet paper",
    "dishwashing liquid","sponges","cleaning sprays","bin liners","matches","candles"
  ],
  "Frozen": [
    "peas","corn","mixed vegetables","broccoli","cauliflower",
    "stir-fry vegetable mix","spinach","edamame","sweet potato",
    "avocado pieces","onions","diced capsicum","blueberries","raspberries",
    "mixed berries","mango","banana","cherries","pineapple","fruit salad",
    "acai puree","smoothie packs","oven fries","potato wedges","hash browns",
    "potato gems","mashed potato","onion rings","crumbed mushrooms",
    "battered cauliflower","vegetable patties","falafel","veggie nuggets",
    "veggie burgers","plant-based mince","plant-based sausages",
    "plant-based chicken","beef mince","chicken breast","chicken nuggets",
    "chicken schnitzels","chicken tenders","chicken wings","chicken kievs",
    "whole chicken","turkey breast","duck","pork roast","beef burgers",
    "steak","meat pies","sausage rolls","pizza","mini pizzas","garlic bread",
    "lasagna","pasta meals","cannelloni","ravioli","gnocchi","pasta sheets",
    "dumplings","gyoza","spring rolls","samosas","roti","naan","paratha",
    "puff pastry","shortcrust pastry","filo pastry","pastry sheets","quiches",
    "savory pastries","fish fillets","salmon portions","prawns","calamari",
    "seafood marinara mix","seafood baskets","fish fingers","crab sticks",
    "dim sims","bao buns","pancakes","waffles","crumpets","croissants",
    "brioche buns","muffins","yorkshire puddings","scones","cakes","cheesecakes",
    "tarts","desserts","ice cream","gelato","sorbit","yoghurt","icy poles",
    "fruit bars","ice cubes","baby food","dog food","cat food"
  ]
}
